### ISSUE TITLE
Error when adding Respro as a Gradle dependency using GitHub Packages

### ISSUE THREAD

**Issue by CodeF53** [null2264/Respro#1]
I am encountering an error when trying to add Respro as a Gradle dependency using GitHub Packages. After following the instructions on the readme file and adding the following line to my Gradle file:
```gradle
modImplementation "lv.cebbys.mcmods:respro:${respro_version}+${minecraft_version}"
include "lv.cebbys.mcmods:respro:${respro_version}+${minecraft_version}"
```
I get the following error message:
```
Could not GET 'https://maven.pkg.github.com/null2264/Respro/lv/cebbys/mcmods/respro/0.3.1+1.19.4/respro-0.3.1+1.19.4.pom'. Received status code 401 from server: Unauthorized
```
I am not sure why this error is occurring and how to fix it. Are there any workarounds or solutions that others have found helpful?

## Steps to Reproduce:
1. Follow the instructions on the readme file to add Respro as a Gradle dependency using GitHub Packages.
2. Build the Gradle project.
3. Encounter the error message.

## Expected behavior:
Respro should be added as a Gradle dependency without any error messages.

**Comment by null2264** [comment]
Turns out GitHub Packages (for Maven) is not "public", you need a token key not only to publish it but also when you want to use the package... I'm searching for another Maven Repository to host Respro, maybe I'll just use jitpack.

**Comment by null2264** [comment]
You can now use JitPack to get Respro, I already updated the guide in `README.md`.
